### ISSUE TITLE
Move personal exclude files from gitignore to git exclude

### ISSUE THREAD

**Issue by paulobruno** [worlddynamics/WorldDynamics.jl#111]
The `exclude` file inside the `.git/info/` folder works the same way as `.gitignore`, but is intended to be used for [user-based ignore patterns](https://stackoverflow.com/a/23305143). This seems to be exactly the case for some entries in our current [gitignore](https://github.com/natema/WorldDynamics.jl/blob/2e970df7075d34b43368167d356fdf38ddb96b3f/.gitignore), like vscode and Mac files.

Therefore, we should remove the unsuited entries from `.gitignore`. To perform this change, all contributors need to ensure that no file ignored file will be pushed, preferably by using their own `exclude` files.

**Comment by natema** [comment]
This has been around enough, but we can expect users to violate this convention. 
While reading over the internet I agree that, git-theoretically speaking, this should be the right usage, consider that even VSCode make it easy to add files to the `gitignore` by just right clicking on them in the Source Control view, while adding them to `exclude` is not immediate.
For that reason, before closing the issue, I propose to add `gitignore` to `gitignore` to avoid accidental updates.

**Comment by paulobruno** [comment]
Some questions:
1. why can we expect users to violate this convention? If anyone tries to push something that breaks it, we can just reject.
2. could you elaborate more about putting `gitignore` inside itself?

**Comment by natema** [comment]
Because, in practice, `gitignore` is commonly used for user-based ignore patterns, to the point that IDEs make it easy to add files to it, while not providing a way to do that for `exclude`.

**Comment by natema** [comment]
In my opinion, to the common one.

**Comment by universmile** [comment]
I would prefer enforcing the usage but I believe that out of convenience, we should opt for the common way...

**Comment by natema** [comment]
@paulobruno let's go for your preferred way (but I'll divert any complaint to you 😜). 
I assign to the issue @Gnumlab and @nastilucia: that's a good exercise.

**Comment by paulobruno** [comment]
From my point-of-view, it should be veeery simple to use the git exclude. 
I hope I'm not wrong...
