### ISSUE TITLE
Solving a system with initial condition of the form $f(0) = g(0)$

### ISSUE THREAD

**Issue by natema** [worlddynamics/WorldDynamics.jl#133]
In some cases when solving a model we have a differential-algebraic system of equations where two variables $f(t)$ and $g(t)$ have an initial condition of the form $f(0) = g(0)$. 
We currently don't have a direct way to input such initial condition in ModelingToolkit. 
We created a thread in the [Julia forum](https://discourse.julialang.org/t/how-to-tell-modelingtoolkit-that-two-variables-have-the-same-initial-conditions-without-computing-them/87999/1) to discuss it, and it seems that we need to open an issue [on ModelingToolkit](https://github.com/SciML/ModelingToolkit.jl) to investigate it further.

**Comment by paulobruno** [comment]
With a solution to this problem, we can remove the indirect initializations on [Population](https://github.com/natema/WorldDynamics.jl/blob/0a37bdf77f5ce0fe379db572220d5301e7a8e628/src/World3/population/common_pop/initialisations.jl) and [Pollution](https://github.com/natema/WorldDynamics.jl/blob/0a37bdf77f5ce0fe379db572220d5301e7a8e628/src/World3/pollution/initialisations.jl).

**Comment by natema** [comment]
I opened [issue #1911 on MTK](https://github.com/SciML/ModelingToolkit.jl/issues/1911).

**Comment by natema** [comment]
@paulobruno I propose to close this as a `wontfix` issue since there's no current plan to provide that functionality in MTK.

**Comment by paulobruno** [comment]
@natema I agree with your proposition.
