### ISSUE TITLE
Improve E4A variable names

### ISSUE THREAD

**Issue by universmile** [worlddynamics/WorldDynamics.jl#166]
We should improve the nomenclature of variables within the `E4A` model by considering the most semantically appropriate option when translating from `Vensim` to `Julia`,  while following good practices and ensuring a clean code style.

**Comment by natema** [comment]
@universmile could you link to the PR closing this?

**Comment by paulobruno** [comment]
Since #167 is not merged yet, I'm reopening this issue.

**Comment by universmile** [comment]
Closed by #167.

**Comment by natema** [comment]
#167 is now merged in dev, therefore I close the issue.
