### ISSUE TITLE
Implement figures of E4A (GL scenario)

### ISSUE THREAD

**Issue by universmile** [worlddynamics/WorldDynamics.jl#168]
At the moment, we are following the `Vensim` implementation of E4A, which includes a set of figures for both the Giant Leap (`GL`) and the Too Little Too Late (`TLTL`) scenarios. Our current implementation corresponds to the `GL` scenario, for which we should implement all its 30 corresponding figures.

**Comment by natema** [comment]
The scenario is now correctly implemented in the [Earth4All repo](https://github.com/worlddynamics/Earth4All.jl). As for figures, the associated documentation provide a detailed tutorial on how to generate them.
