### ISSUE TITLE
Implement scenario and figures of E4A (TLTL scenario) 

### ISSUE THREAD

**Issue by universmile** [worlddynamics/WorldDynamics.jl#169]
As noted in #168, our current implementation corresponds to the Giant Leap (`GL`) scenario of E4A. We should also implement the the Too Little Too Late (`TLTL`) scenario and its corresponding 30 figures. 

There are 24 parameters to change in order to move from one scenario to the other. They can be found within the `Vensim` implementation.

**Comment by natema** [comment]
The scenario is now correctly implemented in the [Earth4All repo](https://github.com/worlddynamics/Earth4All.jl). As for figures, the associated documentation provide a detailed tutorial on how to generate them.
