### ISSUE TITLE
Add documentation link

### ISSUE THREAD

**Issue by aurorarossi** [worlddynamics/WorldDynamics.jl#180]
As a lot of packages have, I suggest adding the link to the dev documentation in the About section (on the right) of the repo.

**Comment by aurorarossi** [comment]
An example:
![image](https://user-images.githubusercontent.com/65721467/202929162-627fa5f5-3250-41b0-a7bc-888fcc55aadd.png)

**Comment by paulobruno** [comment]
Done. Thanks for the suggestion.
