### ISSUE TITLE
Compatibility with ModelingToolkit 9

### ISSUE THREAD

**Issue by rogersamso** [worlddynamics/WorldDynamics.jl#208]
Hi!

I have been playing around with the library, and noticed that adding compatibility with ModelingToolkit 9 would just require replacing:

1.  All instances of `ODESystem(eqs; name)` by `ODESystem(eqs, t; name)`
2. Function `states` by function `unknowns` (see https://github.com/SciML/ModelingToolkit.jl/pull/2432)

And then update the Project.toml file.

If you'd like to make those changes I can do a PR.

Best

**Comment by aurorarossi** [comment]
Yes, that would be really appreciated!
Thank you very much!
