### ISSUE TITLE
Fluctuations of the Crude Birth Rate variable

### ISSUE THREAD

**Issue by universmile** [worlddynamics/WorldDynamics.jl#60]
In few figures of Chapter 2 (Population), the plot corresponding to the `cbr` variable fluctuates. This instability might be related to Issue #59 (e.g., `iphst` parameter).

In the following, we provide a minimal reproducible example.

Source code : 

```
using WorldDynamics

include("../scenarios/pop1_historicalrun.jl")

@named pop = WorldDynamics.World3.Pop1.population()
@named br = WorldDynamics.World3.Pop1.birth_rate()
@named dr = WorldDynamics.World3.Pop1.death_rate()
@named so = WorldDynamics.World3.Pop1.service_output()
@named io = WorldDynamics.World3.Pop1.industrial_output()
@named f = WorldDynamics.World3.Pop1.food()

@variables t

fig_2_88_variables = [
    (so.sopc, 0,   1000,   "sopc"),
    (io.iopc, 0,   1000,   "iopc"),
    (f.fpc,   0,   1000,   "fpc"),
    (pop.pop, 0,   1.6e10, "pop"),
    (br.cbr,  0,   50,     "cbr"),
    (dr.cdr,  0,   50,     "cdr"),
    (dr.le,   0,   80,     "le"),
    (dr.fpu,  0,   1,      "fpu"),
    (br.fce,  0.5, 1,      "fce"),
]

parameters_2_88 = WorldDynamics.World3.Pop1.getparameters()
parameters_2_88[:iphst] = 4000
parameters_2_88[:lt2] = 1900
parameters_2_88[:cio] = 1000
parameters_2_88[:cso] = 1500
parameters_2_88[:cfood] = 2500

system = pop1_historicalrun(params=parameters_2_88)
sol_2_88 = WorldDynamics.solve(system, (1900, 2100))

plotvariables(sol_2_88, (t, 1900, 2100), fig_2_88_variables, name="Fig. 2.88a", showlegend=true, showaxis=true, colored=true)
```

Resulting plot : 

![Fig  2 88a](https://user-images.githubusercontent.com/32130503/191359955-1192fad0-6816-49f0-b25b-ff96a7f1faa8.svg)

**Comment by universmile** [comment]
The issue is related to the method used by the solver. We should find the adequate method.

In the following, we show the plots returned by different methods, namely `Tsit5` (default), `BS5` (for _stiff_ ODE), and `Rosenbrock23`, `TRBDF2`, `Rodas5` (for _non-stiff_ ODE).

Cf. [https://docs.juliahub.com/DifferentialEquations/UQdwS/6.17.1/solvers/ode_solve/#ode_solve](url)

<img width="1282" alt="solvers" src="https://user-images.githubusercontent.com/32130503/191546108-cde27138-d779-42a2-b155-5461e84f0feb.png">

**Comment by natema** [comment]
I had a look at [the Unknown Stiffness section in the docs](https://diffeq.sciml.ai/stable/solvers/ode_solve/#Unknown-Stiffness-Problems), and calling 
```
sol_2_88 = WorldDynamics.solve(system, (1900, 2100), solver=AutoVern9(Rodas5()))
```
gives
![image](https://user-images.githubusercontent.com/2920162/191554420-bea3824b-a87c-4a5a-a430-6318b7f270f0.png)

**Comment by paulobruno** [comment]
We set the default solver to `AutoVern9(Rodas5())`, but I'm still getting the fluctuations.

**Comment by natema** [comment]
> We set the default solver to `AutoVern9(Rodas5())`, but I'm still getting the fluctuations.

This persists on `julia 1.8.1`?

**Comment by paulobruno** [comment]
> > We set the default solver to `AutoVern9(Rodas5())`, but I'm still getting the fluctuations.
> 
> This persists on `julia 1.8.1`?

Yes, it does.

![Screenshot from 2022-09-29 23-10-31](https://user-images.githubusercontent.com/6677872/193142768-8124b7d1-dd9c-4a63-b712-34db54eec4f8.png)

**Comment by universmile** [comment]
I do not get the fluctuations when I move (from Julia `1.7.2`) to Julia `1.8.1`.

![plot_1](https://user-images.githubusercontent.com/32130503/193145888-7e968c39-de2d-4446-b535-204e0bea45f7.svg)

Side information : I am using DifferentialEquations `7.3.0` and  ModelingToolkit `8.16.0`.

**Comment by paulobruno** [comment]
This is very strange, I'm also using those versions.
```
(WorldDynamics) pkg> status
Project WorldDynamics v0.1.0
Status `/home/pdesousa/Documents/git/WorldDynamics/Project.toml`
  [35d6a980] ColorSchemes v3.19.0
  [3da002f7] ColorTypes v0.11.4
⌅ [0c46a032] DifferentialEquations v7.3.0
  [bd48cda9] GraphRecipes v0.5.12
  [615f187c] IfElse v0.1.1
⌅ [961ee093] ModelingToolkit v8.16.0
  [f0f68f2c] PlotlyJS v0.18.9
```

**Comment by natema** [comment]
@paulobruno on Julia 1.8.5 `AutoVern9(Rodas5())` works fine (I instantiated a fresh environment). 
If you still get the issue, we can compare our Manifest files. 
Otherwise, this should be closed as soon as we solve #114 .

**Comment by paulobruno** [comment]
I confirm there are no fluctuations anymore.  

![Screenshot from 2023-05-10 17-57-01](https://github.com/worlddynamics/WorldDynamics.jl/assets/6677872/2db7bf0c-2f04-41e9-aad6-5902f9956d4e)

**Comment by natema** [comment]
Since #114 has been closed and the oscillation disappeared, I close this issue.
