### ISSUE TITLE
Add possibility to load pre-computed solutions

### ISSUE THREAD

**Issue by natema** [worlddynamics/WorldDynamics.jl#68]
It would be good to provide, as artifacts, pre-computed solutions that can e.g. be used to speed up the plotting of figures.

Related to #24.

**Comment by natema** [comment]
As @paulobruno mentioned, most of the time for plotting is due to the package precompilation, so it is probably not worth to clutter the package with those artifacts.

**Comment by paulobruno** [comment]
We don't necessarily have to put the solution inside the package. Giving the user the possibility to do so, even locally, I still think it's a good feature.

**Comment by natema** [comment]
Closed together with #24.
